### ISSUE TITLE
Wrong instruction for interacting with localhost node ?

### ISSUE THREAD

**Issue by balibou** [smartcontractkit/hardhat-starter-kit#40]
In 00_Deploy_Mocks.js l.34 the instruction is `"Please run 'npx hardhat console' to interact with the deployed smart contracts!`

Should it be `npx hardhat node` instead ?

**Comment by fabioDMFerreira** [comment]
The local network should be launched before starting the deployment. Otherwise, the script will exit before reaching the instruction log line.

The `npx hardhat console` instruction allows the interactaction with the smart contracts. See more details [here](https://hardhat.org/guides/hardhat-console.html).

**Comment by balibou** [comment]
@fabioDMFerreira when I run `npx hardhat deploy` without launching local network, the script (00_Deploy_Mocks.js) runs until the end. Maybe I don't get your point ...

**Comment by fabioDMFerreira** [comment]
That's odd, you shouldn't be able to deploy to a local network if you don't have any node running. Wondering where the smart contracts are being deployed.

The correct command to interact with the deployed smart contracts is `npx hardhat console`. The `npx hardhat node` is used to launch a node in the local network.

**Comment by balibou** [comment]
Ok thanks for your feedback :)
