### ISSUE TITLE
Have config be similar to the new hardhat setup

### ISSUE THREAD

**Issue by PatrickAlphaC** [smartcontractkit/hardhat-starter-kit#46]
If you run `npx hardhat` for a new repo, they have a new option called `Create an advanced sample project`. We should set this repo up to match their syntax.

**Comment by PatrickAlphaC** [comment]
Checkout https://github.com/PatrickAlphaC/decentralized-raffle for some context.

That one is also in typescript though

**Comment by shivam-agarwal-0** [comment]
@pappas999 were you able to review the PR?

**Comment by pappas999** [comment]
just went through everything, LGTM. One thing I had to do though (unrelated to your change), was I had to increase the mocha-timeout in hardhat.config.js from 100000 to 300000, because the integration tests on kovan were timing out. Do you get this issue @shivam-agarwal-0 ? Wondering if it's just kovan being slow, my machine, or something else

Either way, that is unrelated to your PR, and if a change to the timeout is required, we can raise a seperate PR for it

**Comment by shivam-agarwal-0** [comment]
@pappas999 I am not facing any timeout issues, all test cases are passing with 100000 value.

**Comment by pappas999** [comment]
thanks @shivam-agarwal-0
