### ISSUE TITLE
Remove `stringToBytes32`

### ISSUE THREAD

**Issue by PatrickAlphaC** [smartcontractkit/hardhat-starter-kit#51]
We don't need to do this. We should just encode the jobid using ethers.

This is best practice anyways.

**Comment by pappas999** [comment]
Hi @shivam-agarwal-0 , thanks for much for volunteering to take on this PR. To action it successfully, you should change the variable in the solidity contract to be a bytes32 instead of a string, and then in any of the hardhat tasks or scripts that interact with the contract, you should use ethers.js library function like the one you specified to convert the string into a bytes32 to pass into the contract

**Comment by shivam-agarwal-0** [comment]
Hey @pappas999 , I have opened a PR for this issue: #62 
Please review and let me know if anything needs to be changed
