### ISSUE TITLE
Wrong requestId in RandomNumberConsumer unit test

### ISSUE THREAD

**Issue by cuckflong** [smartcontractkit/hardhat-starter-kit#84]
The requestId from 
```
const transaction = await randomNumberConsumer.getRandomNumber()
const transactionReceipt = await transaction.wait(1)
const requestId = transactionReceipt.events[0].topics[1]
```
is different to the requestId from the RandomNumberConsumer contract if you log and see them
```
function getRandomNumber() public returns (bytes32 requestId) {
    require(LINK.balanceOf(address(this)) >= fee, "Not enough LINK - fill contract with faucet");
    requestId = requestRandomness(keyHash, fee);
    console.logBytes32(requestId);
  }
```

![image](https://user-images.githubusercontent.com/28383100/155264809-4a0aebc5-4c39-4a98-9443-a18a5964ef4e.png)

**Comment by rgottleber** [comment]
Hi,
It looks like you have code from `RandomNumberConsumer_unit_test.js` as well as `RandomNumberConsumer.sol`

If those are the files you are referencing, the difference in the values is because the first request id 
` transactionReceipt.events[0].topics[1]` is the id of the request to the `RandomNumberConsumer` contract
while
`requestId = requestRandomness(keyHash, fee);` is the id of the request to the `VRF Coordinator` contract.

Closing this for now, but feel free to follow up if more information would help.
